services:
  agilistaapi:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings:DB_Conn=${DB_Conn}
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

    ports:
      - 5114:5114
    depends_on:
      - migration
    
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssword1"
      ACCEPT_EULA: "Y" 
    ports:
      - "1630:1433" 
  migration:
    image: flyway/flyway:latest-alpine
    container_name: flyway_migration_julie
    volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/bin:/flyway/bin
    entrypoint: ["flyway","migrate"]      
    command:  -user=sa -password=P@ssword1 -mixed=true -connectRetries=20 -url='jdbc:sqlserver://db;databaseName=master;trustServerCertificate=true;'
    depends_on:
      - db